# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /auto/homes/hc475/P35/P35_matrix/matrixMul/matrixMul.cache/wt [current_project]
set_property parent.project_path /auto/homes/hc475/P35/P35_matrix/matrixMul/matrixMul.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /auto/homes/hc475/P35/P35_matrix/multiplier.v
  /auto/homes/hc475/P35/P35_matrix/Mat_mult.v
  /auto/homes/hc475/P35/P35_matrix/matrixMul/matrixMul.srcs/sources_1/new/Mat_mul_TB.v
}
synth_design -top Mat_mul_TB -part xc7z010clg400-1
write_checkpoint -noxdef Mat_mul_TB.dcp
catch { report_utilization -file Mat_mul_TB_utilization_synth.rpt -pb Mat_mul_TB_utilization_synth.pb }
