# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/two_by_two_arb_zedboard/two_by_two_arb_zedboard.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_zedboard || ORIG_REF_NAME==two_by_two_arb_zedboard}]

# IP: bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_two_by_two_arb_0_0/two_by_two_arb_zedboard_two_by_two_arb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_zedboard_two_by_two_arb_0_0 || ORIG_REF_NAME==two_by_two_arb_zedboard_two_by_two_arb_0_0}]

# IP: bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_processing_system7_0_0/two_by_two_arb_zedboard_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_zedboard_processing_system7_0_0 || ORIG_REF_NAME==two_by_two_arb_zedboard_processing_system7_0_0}]

# IP: bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_ps7_0_axi_periph_0/two_by_two_arb_zedboard_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_zedboard_ps7_0_axi_periph_0 || ORIG_REF_NAME==two_by_two_arb_zedboard_ps7_0_axi_periph_0}]

# IP: bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_zedboard_rst_ps7_0_50M_0 || ORIG_REF_NAME==two_by_two_arb_zedboard_rst_ps7_0_50M_0}]

# IP: bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_auto_pc_0/two_by_two_arb_zedboard_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_zedboard_auto_pc_0 || ORIG_REF_NAME==two_by_two_arb_zedboard_auto_pc_0}]

# XDC: bd/two_by_two_arb_zedboard/two_by_two_arb_zedboard_ooc.xdc
