# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.cache/wt [current_project]
set_property parent.project_path /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/aaron/Project/P35_matrix/Vivado/Design/two_by_two_arb/ip_repo/two_by_two_arb_1.0 [current_project]
set_property ip_output_repo /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/hdl/two_by_two_arb_zedboard_wrapper.v
add_files /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/two_by_two_arb_zedboard.bd
set_property used_in_implementation false [get_files -all /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_processing_system7_0_0/two_by_two_arb_zedboard_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_auto_pc_0/two_by_two_arb_zedboard_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/two_by_two_arb_zedboard_ooc.xdc]
set_property is_locked true [get_files /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/two_by_two_arb_zedboard.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top two_by_two_arb_zedboard_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef two_by_two_arb_zedboard_wrapper.dcp

catch { report_utilization -file two_by_two_arb_zedboard_wrapper_utilization_synth.rpt -pb two_by_two_arb_zedboard_wrapper_utilization_synth.pb }
