# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0.xci
# IP: The module: 'two_by_two_arb_zedboard_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_by_two_arb_zedboard_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_by_two_arb_zedboard_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_by_two_arb_zedboard_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0.xci
# IP: The module: 'two_by_two_arb_zedboard_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_by_two_arb_zedboard_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_by_two_arb_zedboard_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/aaron/Project/P35_matrix/Vivado/Integrated/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard/two_by_two_integrated_zedboard.srcs/sources_1/bd/two_by_two_arb_zedboard/ip/two_by_two_arb_zedboard_rst_ps7_0_50M_0/two_by_two_arb_zedboard_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_by_two_arb_zedboard_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
