# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /auto/homes/yaz21/P35_project/Integrated/twobytwo_mult_integ/twobytwo_mult_integ.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /auto/homes/yaz21/P35_project/Integrated/twobytwo_mult_integ/twobytwo_mult_integ.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /auto/homes/yaz21/P35_project/Integrated/twobytwo_mult_integ/twobytwo_mult_integ.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /auto/homes/yaz21/P35_project/Integrated/twobytwo_mult_integ/twobytwo_mult_integ.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
