# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/two_by_two_arb_djgboard/two_by_two_arb_djgboard.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_djgboard || ORIG_REF_NAME==two_by_two_arb_djgboard}]

# IP: bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_two_by_two_arb_0_0/two_by_two_arb_djgboard_two_by_two_arb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_djgboard_two_by_two_arb_0_0 || ORIG_REF_NAME==two_by_two_arb_djgboard_two_by_two_arb_0_0}]

# IP: bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_processing_system7_0_0/two_by_two_arb_djgboard_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_djgboard_processing_system7_0_0 || ORIG_REF_NAME==two_by_two_arb_djgboard_processing_system7_0_0}]

# IP: bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_ps7_0_axi_periph_0/two_by_two_arb_djgboard_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_djgboard_ps7_0_axi_periph_0 || ORIG_REF_NAME==two_by_two_arb_djgboard_ps7_0_axi_periph_0}]

# IP: bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_rst_ps7_0_50M_0/two_by_two_arb_djgboard_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_djgboard_rst_ps7_0_50M_0 || ORIG_REF_NAME==two_by_two_arb_djgboard_rst_ps7_0_50M_0}]

# IP: bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_auto_pc_0/two_by_two_arb_djgboard_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==two_by_two_arb_djgboard_auto_pc_0 || ORIG_REF_NAME==two_by_two_arb_djgboard_auto_pc_0}]

# XDC: bd/two_by_two_arb_djgboard/two_by_two_arb_djgboard_ooc.xdc
