# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /auto/homes/yaz21/P35_project/P35_matrix/Vivado/Integrated/two_by_two_arb_integrated/two_by_two_arb_integrated/two_by_two_arb_integrated.srcs/sources_1/bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_processing_system7_0_0/two_by_two_arb_djgboard_processing_system7_0_0.xci
# IP: The module: 'two_by_two_arb_djgboard_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /auto/homes/yaz21/P35_project/P35_matrix/Vivado/Integrated/two_by_two_arb_integrated/two_by_two_arb_integrated/two_by_two_arb_integrated.srcs/sources_1/bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_processing_system7_0_0/two_by_two_arb_djgboard_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_by_two_arb_djgboard_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /auto/homes/yaz21/P35_project/P35_matrix/Vivado/Integrated/two_by_two_arb_integrated/two_by_two_arb_integrated/two_by_two_arb_integrated.srcs/sources_1/bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_processing_system7_0_0/two_by_two_arb_djgboard_processing_system7_0_0.xci
# IP: The module: 'two_by_two_arb_djgboard_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /auto/homes/yaz21/P35_project/P35_matrix/Vivado/Integrated/two_by_two_arb_integrated/two_by_two_arb_integrated/two_by_two_arb_integrated.srcs/sources_1/bd/two_by_two_arb_djgboard/ip/two_by_two_arb_djgboard_processing_system7_0_0/two_by_two_arb_djgboard_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_by_two_arb_djgboard_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
